[package]
name = "whoknows_nooneknows"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.10.0"
bcrypt = "0.15.0"
diesel = { version = "2.1.6", features = ["postgres"] }
dotenvy = "0.15"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["tera_templates", "serve", "json"]

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["diesel_postgres"]
default-features = false

[default.databases.whoknows]
url = "postgres://postgres:postgres@localhost/whoknows"
