[global]
keep_alive = 5
limits = { forms = 32768 }

[default]
address = "127.0.0.1"
port = 8001
log_level = "normal"

[debug]
port = 8000
secret_key = "development key"
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
log_level = "critical"
