[global]
keep_alive = 5
limits = { forms = 32768 }

[default]
address = "127.0.0.1"
port = 8000
log_level = "normal"

[debug]
ROCKET_SECRET_KEY="development key"
log_level = "normal"

[staging]
address = "0.0.0.0"
port = 8001
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
log_level = "critical"
secret_key = { env = "ROCKET_SECRET_KEY" }