[global]
keep_alive = 5
read_timeout = 5
write_timeout = 5
limits = { forms = 32768 }

[default]
address = "localhost"
port = 8000
log = "normal"

[default.databases]
whoknows = { url = "postgres://postgres:postgres@localhost/whoknows" }

[development]
log = "normal"

[staging]
address = "0.0.0.0"
port = 8000
log = "normal"

[staging.databases]
whoknows = { url = "postgres://postgres:postgres@staging-host/whoknows" }

[production]
address = "127.0.0.1"
port = 8000
log = "critical"

[production.databases]
whoknows = { url = ${PROD_DATABASE_URL} }
