name: Deploy to production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true" # Ensure offline mode is enabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install zig
        run: sudo snap install zig --classic --beta

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build the application with deploy.sh
        run: bash deploy.sh

      # ... rest of your steps ...
      - name: copy the tarball to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: ${{ secrets.PKG }}.tar.gz
          target: ${{ secrets.DEPLOY_DIR }}

          # extract and run the app on the VM
      - name: extract and run the app on the VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            rm -rf migrations # Remove the migrations directory
            rm -rf templates # Remove the templates directory
            rm -rf static  # Remove the static directory
            rm -rf Rocket.toml # Remove the Rocket.toml file
            rm ${{ secrets.PKG }} # Remove the old package file
            tar -xzvf ${{ secrets.PKG }}.tar.gz # Extract the new package file
            rm ${{ secrets.PKG }}.tar.gz # Remove the tar.gz file
            sudo rm -rf /var/cache/nginx/ # Clear the Nginx cache
            sudo mkdir -p /var/cache/nginx/ # Create the Nginx cache directory
            sudo systemctl restart ${{ secrets.SERVICE_NAME }}.service # Restart the service
