name: Issue Workflow

on:
  issues:
    types: [opened]

jobs:
  issue_opened:
    runs-on: ubuntu-latest
    # Should make a comment on the issue sayin thanks for opening an issue
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening an issue! We'll get to it as soon as possible.
