name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true" # Ensure offline mode is enabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install zig
        run: sudo snap install zig --classic --beta

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build the application with deploy.sh
        run: bash deploy.sh

      # ... rest of your steps ...
      - name: copy the tarball to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: ${{ secrets.PKG }}.tar.gz
          target: ${{ secrets.STAGING_DIR }}

          # extract and run the app on the VM
      - name: extract and run the app on the VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.STAGING_DIR }}3
            rm -rf migrations
            rm -rf templates
            rm -rf static
            rm -rf Rocket.toml
            rm ${{ secrets.PKG }}
            tar -xzvf ${{ secrets.PKG }}.tar.gz
            rm ${{ secrets.PKG }}.tar.gz
            sudo systemctl restart ${{ secrets.SERVICE_NAME_STAGING }}.service
